// AUTHORIZATION
export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const RECEIVE_LOGIN_STATUS = 'RECEIVE_LOGIN_STATUS'
export const REGISTER_USER = 'REGISTER_USER'
export const REDIRECT_USER = 'REDIRECT_USER'
export const CHANGE_AUTH_STATUS = 'CHANGE_AUTH_STATUS'

//USER POSTS
export const FETCH_USER_POSTS = 'FETCH_USER_POSTS'
export const UPDATE_USER_POSTS = 'UPDATE_USER_POSTS'