// AUTHORIZATION
export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const RECEIVE_LOGIN_STATUS = 'RECEIVE_LOGIN_STATUS'
export const REGISTER_USER = 'REGISTER_USER'
export const REDIRECT_USER = 'REDIRECT_USER'
export const CHECK_AUTH_STATUS = 'CHECK_AUTH_STATUS'
export const CHANGE_AUTH_STATUS = 'CHANGE_AUTH_STATUS'
export const LOGOUT_USER = 'LOGOUT_USER'

//USER POSTS
export const FETCH_USER_POSTS = 'FETCH_USER_POSTS'
export const UPDATE_USER_POSTS = 'UPDATE_USER_POSTS'
export const DELETE_POST = 'DELETE_POST'
export const EDIT_AFTER_DELETE = 'EDIT_AFTER_DELETE'
export const EDIT_POST = 'EDIT_POST'
export const UPDATE_AFTER_EDIT = 'UPDATE_AFTER_EDIT'

//USER INFO 
export const CHANGE_SETTINGS = 'CHANGE_SETTINGS'
export const EDIT_USER = 'EDIT_USER'